import type { SdsDocument } from './types';

export const sdsLocations = ['Industrivej', 'Vestavej', 'Klinkby'];

export const sdsDocuments: SdsDocument[] = [
  {
    id: 'sds-acetylen',
    name: 'Acetylen',
    supplier: 'Air Liquide',
    productNumber: 'AL-1001',
    signalWord: 'Fare',
    hazardCodes: ['H220', 'H280'],
    hazardLabels: ['Yderst brandfarlig gas', 'Gas under tryk'],
    location: 'Industrivej',
    emergencyPhone: '82 12 12 12',
    ppe: ['Beskyttelsesbriller', 'Arbejdshandsker', 'Flammehæmmende tøj'],
    firstAid: {
      eyes: 'Skyl forsigtigt med vand. Fjern eventuelle kontaktlinser.',
      skin: 'Ved kuldeskade skylles med lunkent vand. Søg læge.',
      inhalation: 'Bring personen i frisk luft og hold vedkommende i ro.',
    },
    pdfFileName: 'acetylen-air-liquide.pdf',
    qrCode: 'SDS-ACETYLEN',
    revisionDate: '2026-02-14',
  },
  {
    id: 'sds-natriumhydroxid',
    name: 'Natriumhydroxid 27,65 %',
    supplier: 'Brenntag Nordic',
    productNumber: 'BN-2740',
    signalWord: 'Fare',
    hazardCodes: ['H290', 'H314'],
    hazardLabels: ['Kan ætse metaller', 'Forårsager svære ætsninger'],
    location: 'Vestavej',
    emergencyPhone: '82 12 12 12',
    ppe: ['Ansigtsskærm', 'Kemihandsker', 'Kemikalieforklæde'],
    firstAid: {
      eyes: 'Skyl straks med vand i mindst 15 minutter. Ring 112 eller Giftlinjen.',
      skin: 'Fjern forurenet tøj og skyl huden længe med vand.',
      inhalation: 'Frisk luft. Søg læge ved hoste eller åndedrætsbesvær.',
    },
    pdfFileName: 'natriumhydroxid-brenntag.pdf',
    qrCode: 'SDS-NAOH-2765',
    revisionDate: '2026-04-03',
  },
  {
    id: 'sds-motorolie',
    name: 'Mobil Pegasus 1005',
    supplier: 'ExxonMobil',
    productNumber: 'EM-P1005',
    signalWord: 'Advarsel',
    hazardCodes: ['H304'],
    hazardLabels: ['Kan være livsfarligt ved indtagelse'],
    location: 'Industrivej',
    emergencyPhone: '82 12 12 12',
    ppe: ['Nitrilhandsker', 'Beskyttelsesbriller'],
    firstAid: {
      eyes: 'Skyl med vand i flere minutter.',
      skin: 'Vask grundigt med sæbe og vand.',
      inhalation: 'Flyt til frisk luft ved ubehag.',
    },
    pdfFileName: 'mobil-pegasus-1005.pdf',
    qrCode: 'SDS-MOBIL-P1005',
    revisionDate: '2025-11-18',
  },
  {
    id: 'sds-glykol',
    name: 'Monoethylenglykol',
    supplier: 'Univar Solutions',
    productNumber: 'US-MEG',
    signalWord: 'Advarsel',
    hazardCodes: ['H302', 'H373'],
    hazardLabels: ['Farlig ved indtagelse', 'Kan forårsage organskader'],
    location: 'Klinkby',
    emergencyPhone: '82 12 12 12',
    ppe: ['Kemihandsker', 'Beskyttelsesbriller'],
    firstAid: {
      eyes: 'Skyl med vand. Søg læge ved vedvarende irritation.',
      skin: 'Vask med vand og sæbe.',
      inhalation: 'Sørg for frisk luft og hold personen varm.',
    },
    pdfFileName: 'monoethylenglykol-univar.pdf',
    qrCode: 'SDS-MEG',
    revisionDate: '2026-01-09',
  },
];
