import { getDefaultModuleAccess } from '../../features/auth/roleAccess';
import type { ManagedUser, PortalSettings, SystemCategory, SystemLocation } from './types';

export const roleLabels = {
  system_admin: 'Systemadministrator',
  admin: 'Administrator',
  hr_admin: 'HR-administrator',
  time_admin: 'Tidsadministrator',
  operator: 'Driftsoperatør',
  handyman: 'Facility-medarbejder',
  office: 'Kontor',
  info_screen: 'Infoskærm',
} as const;

export const adminUserSeed: ManagedUser[] = [
  {
    id: 'demo-stefan',
    fullName: 'Stefan',
    email: 'stefan@lemvig-varme.local',
    phone: '',
    jobTitle: 'Driftsleder',
    role: 'system_admin',
    moduleAccess: getDefaultModuleAccess('system_admin'),
    isActive: true,
    updatedAt: '2026-06-30T08:00:00.000Z',
    syncStatus: 'synced',
  },
  {
    id: 'demo-allan',
    fullName: 'Allan',
    email: 'allan@lemvig-varme.local',
    phone: '',
    jobTitle: 'Driftsoperatør',
    role: 'operator',
    moduleAccess: getDefaultModuleAccess('operator'),
    isActive: true,
    updatedAt: '2026-06-29T08:00:00.000Z',
    syncStatus: 'synced',
  },
  {
    id: 'demo-anita',
    fullName: 'Anita',
    email: 'anita@lemvig-varme.local',
    phone: '',
    jobTitle: 'Administration',
    role: 'hr_admin',
    moduleAccess: getDefaultModuleAccess('hr_admin'),
    isActive: true,
    updatedAt: '2026-06-29T08:00:00.000Z',
    syncStatus: 'synced',
  },
  {
    id: 'demo-laurids',
    fullName: 'Laurids',
    email: 'laurids@lemvig-varme.local',
    phone: '',
    jobTitle: 'Driftsoperatør',
    role: 'operator',
    moduleAccess: getDefaultModuleAccess('operator'),
    isActive: true,
    updatedAt: '2026-06-28T08:00:00.000Z',
    syncStatus: 'synced',
  },
  {
    id: 'demo-thomas',
    fullName: 'Thomas',
    email: 'thomas@lemvig-varme.local',
    phone: '',
    jobTitle: 'Facility-medarbejder',
    role: 'handyman',
    moduleAccess: getDefaultModuleAccess('handyman'),
    isActive: true,
    updatedAt: '2026-06-28T08:00:00.000Z',
    syncStatus: 'synced',
  },
];

export const locationSeed: SystemLocation[] = [
  {
    id: 'location-industrivej',
    name: 'Industrivej',
    code: 'IND',
    address: 'Industrivej, Lemvig',
    isActive: true,
    updatedAt: '2026-06-30T08:00:00.000Z',
    syncStatus: 'synced',
  },
  {
    id: 'location-vestavej',
    name: 'Vestavej',
    code: 'VES',
    address: 'Vestavej, Lemvig',
    isActive: true,
    updatedAt: '2026-06-30T08:00:00.000Z',
    syncStatus: 'synced',
  },
  {
    id: 'location-klinkby',
    name: 'Klinkby',
    code: 'KLI',
    address: 'Klinkby, Lemvig',
    isActive: true,
    updatedAt: '2026-06-30T08:00:00.000Z',
    syncStatus: 'synced',
  },
];

export const categorySeed: SystemCategory[] = [
  {
    id: 'category-drift',
    name: 'Drift',
    area: 'Opgaver',
    color: '#00e5ff',
    isActive: true,
    updatedAt: '2026-06-30T08:00:00.000Z',
    syncStatus: 'synced',
  },
  {
    id: 'category-elektrisk',
    name: 'Elektrisk',
    area: 'Opgaver',
    color: '#fbbf24',
    isActive: true,
    updatedAt: '2026-06-30T08:00:00.000Z',
    syncStatus: 'synced',
  },
  {
    id: 'category-mekanisk',
    name: 'Mekanisk',
    area: 'Opgaver',
    color: '#fb923c',
    isActive: true,
    updatedAt: '2026-06-30T08:00:00.000Z',
    syncStatus: 'synced',
  },
  {
    id: 'category-kemikalier',
    name: 'Kemikalier',
    area: 'Lager',
    color: '#f472b6',
    isActive: true,
    updatedAt: '2026-06-30T08:00:00.000Z',
    syncStatus: 'synced',
  },
];

export const settingsSeed: PortalSettings = {
  organizationName: 'Lemvig Varmeværk',
  emergencyPhone: '82 12 12 12',
  defaultLocationId: 'location-industrivej',
  syncIntervalMinutes: 15,
  automaticSync: true,
  pushNotifications: false,
  offlineMode: true,
  updatedAt: '2026-06-30T08:00:00.000Z',
  syncStatus: 'synced',
};
