import type { Meter, MeterReading } from './types';

export const meters: Meter[] = [
  {
    id: 'biogas-ge-620',
    name: 'Biogas GE 620',
    location: 'Vestavej',
    group: 'Produktion',
    unit: 'm³',
    intervalHours: 24,
    minValue: 0,
    maxValue: 999999,
    averageConsumption: 245,
    status: 'due',
    qrCode: 'meter:biogas-ge-620',
    note: 'Aflæses dagligt i SRO.',
  },
  {
    id: 'elproduktion-gm1',
    name: 'Elproduktion motor GM 1',
    location: 'Vestavej',
    group: 'El',
    unit: 'kWh',
    intervalHours: 24,
    averageConsumption: 4300,
    status: 'alarm',
    qrCode: 'meter:elproduktion-gm1',
  },
  {
    id: 'varmeproduktion-ahp',
    name: 'Varmeproduktion AHP',
    location: 'Vestavej',
    group: 'Varme',
    unit: 'MWh',
    intervalHours: 24,
    averageConsumption: 42,
    status: 'due',
    qrCode: 'meter:varmeproduktion-ahp',
  },
  {
    id: 'kondensat-vestavej',
    name: 'Kondensat',
    location: 'Vestavej',
    group: 'Vand',
    unit: 'm³',
    intervalHours: 48,
    averageConsumption: 18,
    status: 'ok',
    qrCode: 'meter:kondensat-vestavej',
  },
  {
    id: 'elmåler-varmepumpe-gm1',
    name: 'Elmåler varmepumpe GM 1',
    location: 'Vestavej',
    group: 'El',
    unit: 'kWh',
    intervalHours: 24,
    averageConsumption: 1250,
    status: 'service',
    qrCode: 'meter:elmaaler-varmepumpe-gm1',
    note: 'Markeret til kontrol efter næste aflæsning.',
  },
];

export const readings: MeterReading[] = [
  {
    id: 'reading-1',
    meterId: 'biogas-ge-620',
    value: 842120,
    readAt: '2026-06-24T08:02:00.000Z',
    readBy: 'Stefan',
  },
  {
    id: 'reading-2',
    meterId: 'biogas-ge-620',
    value: 841870,
    readAt: '2026-06-23T08:01:00.000Z',
    readBy: 'Allan',
  },
  {
    id: 'reading-3',
    meterId: 'elproduktion-gm1',
    value: 1203400,
    readAt: '2026-06-23T08:05:00.000Z',
    readBy: 'Thomas',
    comment: 'Høj produktion efter natdrift.',
  },
  {
    id: 'reading-4',
    meterId: 'varmeproduktion-ahp',
    value: 9912,
    readAt: '2026-06-24T08:06:00.000Z',
    readBy: 'Stefan',
  },
  {
    id: 'reading-5',
    meterId: 'kondensat-vestavej',
    value: 512,
    readAt: '2026-06-25T06:58:00.000Z',
    readBy: 'Laurids',
  },
];
